stages:
- build latex

.phony: &base_latex
  image: registry.gitlab.com/pep10/writing/latex:v1.1.1
  stage: build latex

Build:
  <<: *base_latex
  artifacts:
    paths:
    - pep10-documentation.pdf
  script:
    - latexmk -xelatex pep10-documentation.tex
