variables:
  GIT_LFS_SKIP_SMUDGE: '1'

stages:
  - build
  - test
  - chromatic
  - deploy

# Enable npm caching on all stages
.cacheable-node: &cacheable-node 
  image: node:16.11.0
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

# Commands
.build: &build
  stage: build
  script:
    - npm run build

.test: &test
  stage: test
  script:
    - npm run test:ci
    - cp ./junit.xml ../junit.xml
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit:
        - packages/junit.xml

# Packages
.ui-sample: &ui-sample
  <<: *cacheable-node
  before_script:
    - cd packages/ui-sample
    - npm ci

build:ui-sample:
  <<: *ui-sample
  <<: *build

test:ui-sample:
  <<: *ui-sample
  <<: *test