variables:
  GIT_LFS_SKIP_SMUDGE: '1'

stages:
  - build
  - test
  - chromatic
  - deploy

# Enable npm caching on all stages
.cacheable-node: &cacheable-node 
  image: node:16.11.0
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

# Commands
.build: &build
  stage: build
  script:
    - npm run build

.test: &test
  stage: test
  script:
    - npm run test:ci
    - cp ./junit.xml ../junit.xml
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit:
        - packages/junit.xml

# Packages
.ui-sample: &ui-sample
  <<: *cacheable-node
  before_script:
    - cd packages/ui-sample
    - npm ci

build:ui-sample:
  <<: *ui-sample
  <<: *build

test:ui-sample:
  <<: *ui-sample
  <<: *test

# Chromatic test
test:chromatic:
  <<: *cacheable-node
  stage: chromatic
  needs: ['test:ui-sample']
  script:
    - cd packages
    - npm ci
    - npx chromatic --exit-zero-on-changes --project-token ${CHROMATIC_PROJECT_TOKEN} --junit-report junit.xml
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == 'dev'
      when: on_success
      changes:
        - packages/**/*
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit:
        - packages/junit.xml